pull_request_title: "feat(lang): update translations"
commit_message: "feat(lang): new translations (%language%)"
append_commit_message: false
files:
  - source: /src/i18n/strings.json
    translation: /src/i18n/%two_letters_code%.json
