name: 'custom-changelog-action'
description: 'Generates changelogs for commitlint commits.'
author: 'Tormak'
inputs:
  github-token:
    description: "Github token"
    default: ${{ github.token }}
    required: false
    
  git-message:
    description: "Commit message to use"
    default: "chore(release): {version}"
    required: false

  git-user-name:
    description: "The git user.name to use for the commit"
    default: "Conventional Changelog Action"
    required: false

  git-user-email:
    description: "The git user.email to use for the commit"
    default: "conventional.changelog.action@github.com"
    required: false

  git-pull-method:
    description: "The git pull method used when pulling all changes from remote"
    default: "--ff-only"
    required: false

  git-branch:
    description: "The git branch to be pushed"
    default: ${{ github.ref }}
    required: false

  tag-prefix:
    description: "Prefix that is used for the git tag"
    default: "v"
    required: false

  git-url:
    description: "Git Url"
    default: "github.com"
    required: false
    
outputs:
  clean_changelog:
    description: "A tidied version of the generated changelog."

  tag:
    description: "The tag for the new release."

  version:
    description: "The version for the new release."

runs:
  using: 'node16'
  main: 'action-dist/index.cjs'
